### ISSUE TITLE
EXE not found

### ISSUE THREAD

**Issue by Vanilla009** [Thermionix/fusion360#26]
I followed the instructions and I received this error message at the end:
removed '/tmp/Fusion%20360%20Admin%20Install.exe'
Running hook '/snap/fusion360/16/sommelier/hooks/post-install'
updated RUN_EXE=
Starting application..
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

I can give the rest of the output if you need it.

**Comment by zacharytomlinson** [comment]
@Vanilla009 Same issue here

**Comment by Auverus** [comment]
Any fixes? It was working fine before.

**Comment by fattylipidacid** [comment]
same here on ubuntu 22.04 - happy to provide logs and info if im told which

**Comment by aeonsablaze** [comment]
Same issue here on Fedora 39.

**Comment by jh0l** [comment]
Testing the URL for the installer used in the snapcraft.yaml - when I run `wget https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe` I get 403: forbidden - looks like they don't want non browser users downloading the installer?

**Comment by Johnny1070** [comment]
Just added pull request with current admin installer, outlined in [this](https://forums.autodesk.com/t5/fusion-educators/fusion-360-admin-install-in-2024/m-p/12537406/highlight/true#M5292) thread

**Comment by root-hal9000** [comment]
@Johnny1070 I assume this merge has not been published to the snapstore, right? Because I am getting the same error. I am trying to build from source now, but just checking if I understood. I hope it works, hanging on "Starting snapcraft-fusion360" for a while now. Really excited about this, fusion 360 is the only thing that has kept me having to use windows at all (and going into the rabbit hole of VM GPU passthrough)

**Comment by StdVectorBool** [comment]
@Thermionix Could you publish that latest URL fix?

**Comment by nordstream3** [comment]
@StdVectorBool Please, could you give the "command line" for running fusion360 using "snap try"?

**Comment by StdVectorBool** [comment]
> @StdVectorBool Please, could you give the "command line" for running fusion360 using "snap try"?

1. Find the name of your Fusion 360 snap file: `ls /var/lib/snapd/snaps/fusion*`
2. Extract it to `squashfs-root` in your home directory: `unsquashfs ls /var/lib/snapd/snaps/<FUSION_SNAP>`
3. Go into `squashfs-root` and update `INSTALL_URL` according to the [PR](https://github.com/Thermionix/fusion360/pull/27/files)
4. Mount that modification: `snap try squashfs-root`

Unfortunately this still has the issue that it can't login because of the browser, and the `FUSION_IDSDK` workaround has been disabled as of January 2024.

**Comment by Thermionix** [comment]
pushed new build to snapcraft

**Comment by nordstream3** [comment]
@StdVectorBool
I build the snap from source calling:
./build_test.sh

Then installing like this:
sudo snap install --devmode fusion360_1.2_amd64.snap

And running:
env FUSION_IDSDK=false fusion360

Took me all the way to "SIGN IN"  .... but FUSION_IDSDK=false workaround doesn't work anymore...
![image](https://github.com/Thermionix/fusion360/assets/129880401/37deeab8-d7cd-4eaf-b3d2-f3efa395cef5)

**Comment by Thermionix** [comment]
fusion360 installer currently failing due to [wine issue](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/408), I've pushed a [merge request to winehq](https://gitlab.winehq.org/wine/wine/-/merge_requests/5525)
